from rest_framework.decorators import api_view
from rest_framework.response import Response

@api_view(['POST'])
def generate_code(request):
    component = request.data.get('component', 'button')
    code = f"<{component}>Generated by Django</{component}>"
    return Response({"code": code})
