version: "3.9"
services:
  django:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./app-maker/backend:/app/backend
    command: ["python", "backend/manage.py", "runserver", "0.0.0.0:8000"]

  react:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - ./app-maker/frontend/app-builder:/app/frontend
    command: ["npm", "run", "dev"]
